name: Arizona Technology Consultants
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2030012330505997
title: Arizona Technology Consultants - Call Us @ (623)272-9715
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-28691169-
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#891c21'
    - '#d8bbbe'
    - '#b27263'
    - '#943d40'
  brandStrength: 0.011896662646904588
  lightness: 0.37119034747593105
  saturation: 0.4742854905780405
  rhythmicContrast: 0.25660529476590455
purpose: []
