name: Arizona Technology Consultants
favicon: null
layout_spectrum: 0.5240857328753918
typography_spectrum: 0.2030012330505997
title: Arizona Technology Consultants - Call Us @ (623)272-9715
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-28691169-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.011896662646904588
  lightness: 0.37119034747593105
  saturation: 0.4742854905780405
  rhythmicContrast: 0.25660529476590455
purpose: []
